clc;
clear;
gamma=0.05;
epsilon=8*gamma;
T_s=12*gamma;
T_d=2*gamma;
t=0.2*gamma;
phi=5*pi/2;
w=linspace(-2,2,100000);
v=linspace(0,0.577487,1000);
mu_s=-v/2;
mu_d=v/2;
for i=1:1:length(v)
    for j=1:1:length(w)
               
        
        fs(j,i)=1./(exp((w(j)-mu_s(i))/T_s)+1);
        fd(j,i)=1./(exp((w(j)-mu_d(i))/T_d)+1);
        num(j)=4.*gamma.^2.*t.^2.*((epsilon+(-1).*w(j)+t).*((-1).*epsilon+w(j)+t) ...
         .*cos((1/4).*phi)+t.*((epsilon+(-1).*w(j)).*cos((1/2).*phi)+(-1).* ...
         t.*cos((3/4).*phi))).^2;
          deno(j)=(1/16).*((gamma.^2+4.*(epsilon+(-1).*w(j)).^2).*(9.*gamma.^2+4.*( ...
  epsilon+(-1).*w(j)).^2).*(epsilon+(-1).*w(j)).^4+(-4).*(gamma.^4+ ...
  28.*gamma.^2.*(epsilon+(-1).*w(j)).^2+32.*(epsilon+(-1).*w(j)).^4) ...
  .*(epsilon+(-1).*w(j)).^2.*t.^2+2.*(3.*gamma.^4+56.*gamma.^2.*( ...
  epsilon+(-1).*w(j)).^2+160.*(epsilon+(-1).*w(j)).^4).*t.^4+32.*( ...
  3.*gamma.^2+(-8).*(epsilon+(-1).*w(j)).^2).*t.^6+96.*t.^8+(-8).* ...
  gamma.^2.*(epsilon+(-1).*w(j)).*t.*(3.*(gamma.^2+4.*(epsilon+(-1) ...
  .*w(j)).^2).*(epsilon+(-1).*w(j)).^2+(-1).*(gamma.^2+24.*(epsilon+ ...
  (-1).*w(j)).^2).*t.^2+24.*t.^4).*cos((1/4).*phi)+2.*t.^2.*((-2).* ...
  gamma.^2.*((-1).*(5.*gamma.^2+36.*(epsilon+(-1).*w(j)).^2).*( ...
  epsilon+(-1).*w(j)).^2+2.*(gamma.^2+24.*(epsilon+(-1).*w(j)).^2).* ...
  t.^2+12.*t.^4).*cos((1/2).*phi)+(-4).*gamma.^2.*(epsilon+(-1).*w( ...
  j)).*t.*(gamma.^2+24.*(epsilon+(-1).*w(j)).^2+(-36).*t.^2).*cos(( ...
  3/4).*phi)+t.^2.*(gamma.^4+72.*gamma.^2.*(epsilon+(-1).*w(j)).^2+( ...
  -32).*(epsilon+(-1).*w(j)).^4+(-16).*(3.*gamma.^2+(-8).*(epsilon+( ...
  -1).*w(j)).^2).*t.^2+(-64).*t.^4).*cos(phi)+48.*gamma.^2.*((-1).* ...
  epsilon+w(j)).*t.^3.*cos((5/4).*phi)+24.*gamma.^2.*t.^4.*cos((3/2) ...
  .*phi)+16.*t.^6.*cos(2.*phi)));
    T(j)=num(j)./deno(j);
    f(j,i)=T(j).*(fs(j,i)-fd(j,i));
    g(j,i)=(w(j)-mu_s(i)).*f(j,i);
                  end
               
    
    I(i)=trapz(w,f(:,i));
    Q(i)=trapz(w,g(:,i));
    P(i)=(mu_d(i)-mu_s(i)).*I(i);
    eta(i)=P(i)./Q(i);
        end
  eta_c=1-T_d/T_s;
  y=eta/eta_c;
  
figure       
plot(P,y,'LineWidth',2.5)
xlabel('P')
ylabel('\eta/\eta_c')
figure
plot(w-epsilon,T,'LineWidth',2.5)
xlabel('\omega-\epsilon')
ylabel('T_{4QD(3,1)}')