clc;
clear;
T_s=0.6;
T_d=0.1;

gammad=0.05;
gammas=gammad;
t=0.05;
epsilon=0.4;
phi=5*pi/2;
w=linspace(-2,2,100000);
v=linspace(0,0.5530,1000);
mu_s=-v/2;
mu_d=v/2;
for i=1:1:length(v)
for j=1:1:length(w)
    fs(j,i)=1./(exp((w(j)-mu_s(i))/T_s)+1);
    fd(j,i)=1./(exp((w(j)-mu_d(i))/T_d)+1);
    num(j)=4.*gammad.*gammas.*t.^2.*(cos((1/5).*phi).*((-2).*t.^2+(epsilon+( ...
  -1).*w(j)).^2).*(epsilon+(-1).*w(j))+t.*(t.*((-1).*t.*cos((4/5).* ...
  phi)+2.*cos((3/5).*phi).*(epsilon+(-1).*w(j)))+2.*cos((2/5).*phi) ...
  .*(epsilon+t+(-1).*w(j)).*((-1).*epsilon+t+w(j)))).^2;
    deno(j)=(1/4).*(4.*t.^5.*cos(phi)+2.*(5.*t.^4+(-5).*t.^2.*(epsilon+(-1).* ...
  w(j)).^2+(epsilon+(-1).*w(j)).^4).*(epsilon+(-1).*w(j))+(sqrt(-1)* ...
  (-1)).*gammas.*(4.*t.^4.*cos((4/5).*phi)+(-4).*t.*cos((1/5).*phi) ...
  .*((-2).*t.^2+(epsilon+(-1).*w(j)).^2).*(epsilon+(-1).*w(j))+2.* ...
  t.^3.*cos((3/5).*phi).*((-1).*epsilon+w(j))+(-2).*t.^2.*cos((2/5) ...
  .*phi).*(epsilon+t+(-1).*w(j)).*((-1).*epsilon+t+w(j))+3.*(t.^2+ ...
  t.*(epsilon+(-1).*w(j))+(-1).*(epsilon+(-1).*w(j)).^2).*(t.^2+(-1) ...
  .*(epsilon+(-1).*w(j)).^2+t.*((-1).*epsilon+w(j))))+gammad.*((-1) ...
  .*gammas.*(t.^3.*cos((3/5).*phi)+t.*cos((1/5).*phi).*(3.*t.^2+(-7) ...
  .*(epsilon+(-1).*w(j)).^2)+((-2).*t.^2+3.*t.^2.*cos((2/5).*phi)+ ...
  3.*(epsilon+(-1).*w(j)).^2).*(epsilon+(-1).*w(j)))+(sqrt(-1)*(-2)) ...
  .*(t.^4.*cos((4/5).*phi)+(-1).*t.*cos((1/5).*phi).*((-2).*t.^2+( ...
  epsilon+(-1).*w(j)).^2).*(epsilon+(-1).*w(j))+(t.^2+t.*(epsilon+( ...
  -1).*w(j))+(-1).*(epsilon+(-1).*w(j)).^2).*(t.^2+(-1).*(epsilon+( ...
  -1).*w(j)).^2+t.*((-1).*epsilon+w(j)))))).*(4.*t.^5.*cos(phi)+2.*( ...
  5.*t.^4+(-5).*t.^2.*(epsilon+(-1).*w(j)).^2+(epsilon+(-1).*w(j)) ...
  .^4).*(epsilon+(-1).*w(j))+sqrt(-1).*gammas.*(4.*t.^4.*cos((4/5).* ...
  phi)+(-4).*t.*cos((1/5).*phi).*((-2).*t.^2+(epsilon+(-1).*w(j)) ...
  .^2).*(epsilon+(-1).*w(j))+2.*t.^3.*cos((3/5).*phi).*((-1).* ...
  epsilon+w(j))+(-2).*t.^2.*cos((2/5).*phi).*(epsilon+t+(-1).*w(j)) ...
  .*((-1).*epsilon+t+w(j))+3.*(t.^2+t.*(epsilon+(-1).*w(j))+(-1).*( ...
  epsilon+(-1).*w(j)).^2).*(t.^2+(-1).*(epsilon+(-1).*w(j)).^2+t.*(( ...
  -1).*epsilon+w(j))))+gammad.*((-1).*gammas.*(t.^3.*cos((3/5).*phi) ...
  +t.*cos((1/5).*phi).*(3.*t.^2+(-7).*(epsilon+(-1).*w(j)).^2)+((-2) ...
  .*t.^2+3.*t.^2.*cos((2/5).*phi)+3.*(epsilon+(-1).*w(j)).^2).*( ...
  epsilon+(-1).*w(j)))+(sqrt(-1)*2).*(t.^4.*cos((4/5).*phi)+(-1).* ...
  t.*cos((1/5).*phi).*((-2).*t.^2+(epsilon+(-1).*w(j)).^2).*( ...
  epsilon+(-1).*w(j))+(t.^2+t.*(epsilon+(-1).*w(j))+(-1).*(epsilon+( ...
  -1).*w(j)).^2).*(t.^2+(-1).*(epsilon+(-1).*w(j)).^2+t.*((-1).* ...
  epsilon+w(j))))));
    T(j)=num(j)./deno(j);
    f(j,i)=T(j).*(fs(j,i)-fd(j,i));
    g(j,i)=(w(j)-mu_s(i)).*f(j,i);
 end
               
    
    I(i)=trapz(w,f(:,i));
    Q(i)=trapz(w,g(:,i));
    P(i)=(mu_d(i)-mu_s(i)).*I(i);
    eta(i)=P(i)./Q(i);
       end
 eta_c=1-T_d/T_s;
 y=eta/eta_c;
figure
plot(P,y,'LineWidth',2.5)
xlabel('P')
ylabel('\eta/\eta_c')
figure
plot(w-epsilon,T,'LineWidth',2.5)
xlabel('\omega-\epsilon')
ylabel('T_{5QD(3,2)}')